//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        public int Id { get; set; }
        public string Fullname { get; set; }
        public string Grade { get; set; }
        public string ClassNo { get; set; }
    }
}
